PaymentGateway/Areas/ControlPanel/Controllers/MailTemplateController.cs
using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Models;
using StreamAMG.OTTPlatform.Core.Models;
using StreamAMG.OTTPlatform.Core.Services;
using NLog;
using System;
using System.Web.Mvc;

namespace StreamAMG.OTTPlatform.Areas.ControlPanel.Controllers
{
    [RouteArea("ControlPanel")]
    public class MailTemplateController : Controller
    {
        #region Index

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/mailtemplate")]
        public ActionResult Index()
        {
            var searchRequest = new MailService.GetMailTemplateListRequest
            {
                PageIndex = 0,
                PageSize = 20
            };

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pageindex"]))
                searchRequest.PageIndex = Convert.ToInt32(Request.QueryString["pageindex"]);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pagesize"]))
                searchRequest.PageSize = Convert.ToInt32(Request.QueryString["pagesize"]);

            var searchResult = MailService.GetMailTemplateList(searchRequest);
            return View(searchResult);
        }

        #endregion

        #region Edit
        
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/mailtemplate/{mailTemplateId}")]
        public ActionResult Edit(string mailTemplateId)
        {

            
            var getMailtemplateRepsonse = MailService.GetMailtemplate(new MailService.GetMailTemplateRequest { 
                 MailTemplateId = mailTemplateId
            });

            var model = new MailTemplateEditViewModel
            {
                Subject = getMailtemplateRepsonse.MailTemplate.Subject,
                Body = getMailtemplateRepsonse.MailTemplate.Body
            };

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/mailtemplate/{mailTemplateId}")]
        public ActionResult Edit(string mailTemplateId, MailTemplateEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var setCustomerProfileResponse = MailService.SetMailtemplate(new MailService.SetMailTemplateRequest
                {
                    MailTemplateId = mailTemplateId,
                    MailTemplate = new MailTemplateModel
                    {
                        Subject = model.Subject,
                        Body = model.Body                        
                    }
                });
                ViewBag.Success = true;
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to save Mail Template. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }

            return View(model);
        }

        #endregion


        #region Edit

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/mailtemplate/{mailTemplateId}/translate/{language}/")]
        public ActionResult EditTransaltion(string mailTemplateId, string language)
        {

            var mailTemplatePlanGetResponse = MailService.GetMailtemplate(
                new MailService.GetMailTemplateRequest {
                    MailTemplateId = mailTemplateId
                }
            );
            var mailTemplatePlanTransaltionGetResponse = MailService.GetMailTemplateTransaltion(
                new MailService.GetMailTemplateTranslationRequest {
                    MailTemplateId = mailTemplateId,
                    Language = language
                }
            );
       
            var model = new MailTemplateEditTranslationViewModel
            {
                SubjectOriginal = mailTemplatePlanGetResponse.MailTemplate.Subject,
                Subject = mailTemplatePlanTransaltionGetResponse.MailTemplateTranslation.Subject,
                BodyOriginal = mailTemplatePlanGetResponse.MailTemplate.Body,
                Body = mailTemplatePlanTransaltionGetResponse.MailTemplateTranslation.Body
            };

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/mailtemplate/{mailTemplateId}/translate/{language}/")]        
        public ActionResult EditTransaltion(string mailTemplateId, string language, MailTemplateEditTranslationViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var setMailTemplateTranslationResponse = MailService.SetMailTemplateTranslation(new MailService.SetMailTemplateTranslationRequest
                {
                    MailTemplateId = mailTemplateId,
                    Language = language,
                     MailTemplateTranslation = new MailTemplateTranslationModel
                     {
                        Subject = model.Subject,
                        Body = model.Body
                    }
                });
                ViewBag.Success = true;
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to save Mail Template Translation. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }

            return View(model);
        }

        #endregion
    }
}

PaymentGateway/Areas/ControlPanel/Views/MailTemplate/Edit.cshtml
@model StreamAMG.OTTPlatform.Areas.ControlPanel.Models.MailTemplateEditViewModel
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Mail Template";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
}
<script src="~/Areas/ControlPanel/_resx/js/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: '#Body',
        menu: {},
        toolbar: "bold italic underline | alignleft aligncenter alignright alignjustify alignnone | fontselect fontsizeselect | link unlink | bullist numlist outdent indent | table"
    });
</script>

<div class="btn-group pull-right">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            if ((ViewContext.RouteData.Values["language"] == null && StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language)) || (ViewContext.RouteData.Values["language"] != null && language == ViewContext.RouteData.Values["language"].ToString()))
            {
                <img src="/areas/controlpanel/_resx/images/languages/@(language).png" /> @(StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language)) <span class="caret"></span>
            }
        }
    </button>
    <ul class="dropdown-menu">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            <li>
                <a href="/controlpanel/mailtemplate/@ViewContext.RouteData.Values["mailtemplateid"]@( StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language) ? "" : "/translate/" + language)/?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">
                    <img src="/areas/controlpanel/_resx/images/languages/@(language).png" />
                    @( StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language))
                </a>
            </li>
        }
    </ul>
</div>

<h1>Update Email Template</h1>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @Html.ValidationSummary()
    </div>
}
@if (ViewBag.Success == true)
{
    <div class="alert alert-success" role="alert">
        <p>Your changes were successfully saved.</p>
    </div>
}

@if (ViewBag.Success == false)
{
    <div class="alert alert-danger" role="alert">
        <p>Your changes could not be saved please try again.</p>
    </div>
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(m => m.Subject, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(m => m.Body, new { @class = "control-label" })
                @Html.TextAreaFor(m => m.Body, new { @class = "form-control", @rows = 30 })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-actions pull-right">
                <button type="submit" class="btn btn-info">Save <span class="visible-xxxs">changes</span></button>
            </div>
            <div class="form-group">
                <a href="@Request.QueryString["returnurl"]">Return to email template listing</a>
            </div>
        </div>
    </div>
}

PaymentGateway/Areas/ControlPanel/Views/MailTemplate/EditTransaltion.cshtml
@model StreamAMG.OTTPlatform.Areas.ControlPanel.Models.MailTemplateEditTranslationViewModel
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Mail Template";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
}
<script src="~/Areas/ControlPanel/_resx/js/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: '#Body',
        menu: {},
        toolbar: "bold italic underline | alignleft aligncenter alignright alignjustify alignnone | fontselect fontsizeselect | link unlink | bullist numlist outdent indent | table"
    });
</script>
<div class="btn-group pull-right">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            if ((ViewContext.RouteData.Values["language"] == null && StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language)) || (ViewContext.RouteData.Values["language"] != null && language == ViewContext.RouteData.Values["language"].ToString()))
            {
                <img src="/areas/controlpanel/_resx/images/languages/@(language).png" /> @(StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language)) <span class="caret"></span>
            }
        }
    </button>
    <ul class="dropdown-menu">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            <li>
                <a href="/controlpanel/mailtemplate/@ViewContext.RouteData.Values["mailtemplateid"]@( StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language) ? "" : "/translate/" + language)/?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">
                    <img src="/areas/controlpanel/_resx/images/languages/@(language).png" />
                    @( StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language))
                </a>
            </li>
        }
    </ul>
</div>

<h1>Update Email Template</h1>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @Html.ValidationSummary()
    </div>
}
@if (ViewBag.Success == true)
{
    <div class="alert alert-success" role="alert">
        <p>Your changes were successfully saved.</p>
    </div>
}

@if (ViewBag.Success == false)
{
    <div class="alert alert-danger" role="alert">
        <p>Your changes could not be saved please try again.</p>
    </div>
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(m => m.Subject, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" , @placeholder = Model.SubjectOriginal })
                @Html.HiddenFor(m => m.SubjectOriginal)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(m => m.Body, new { @class = "control-label" })
                @Html.TextAreaFor(m => m.Body, new { @class = "form-control", @rows = 30, @placeholder = Model.BodyOriginal })
                @Html.HiddenFor(m => m.BodyOriginal)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-actions pull-right">
                <button type="submit" class="btn btn-info">Save <span class="visible-xxxs">changes</span></button>
            </div>
            <div class="form-group">
                <a href="@Request.QueryString["returnurl"]">Return to email template listing</a>
            </div>
        </div>
    </div>
}

PaymentGateway/Areas/ControlPanel/Views/MailTemplate/Index.cshtml
@model MailService.GetMailTemplateListResult
@using StreamAMG.OTTPlatform.Core.Services;
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Email Templates";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
}
<h1>Email Templates</h1>
<div class="table-responsive">
    <table id="customersTable" class="table table-striped">
        <thead>
            <tr>
                <th>Subject</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.ItemCount == 0)
            {
                <tr>
                    <td class="center" colspan="5">
                        The are currently no email templates
                    </td>
                </tr>
            }
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td data-title="Subject">
                        <strong>@item.Id</strong><br/>
                        @item.Subject
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","MailTemplate",new { @mailTemplateId = item.Id })?returnurl=@HttpUtility.UrlEncode(Request.RawUrl)" class="btn btn-primary">View</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@HtmlExtensions.Pager(Model.PageIndex, Model.PageSize, Model.ItemCount)