PaymentGateway/Areas/ControlPanel/Controllers/TransactionController.cs
using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Models;
using StreamAMG.OTTPlatform.Core.Services;
using System;
using System.Text.RegularExpressions;
using System.Web.Mvc;

namespace StreamAMG.OTTPlatform.Areas.ControlPanel.Controllers
{
    [RouteArea("ControlPanel")]
    public class TransactionController : Controller
    {

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/transaction")]
        public ActionResult Index()
        {
            var exportToCsv = !string.IsNullOrWhiteSpace(Request.QueryString["export"]);
            var searchRequest = new CustomerTransactionService.TransationSearchRequest
            {
                PageIndex = 0,
                PageSize = exportToCsv ? int.MaxValue : 20
            };

            searchRequest.DateTo = DateTime.UtcNow;
            searchRequest.DateFrom = DateTime.UtcNow.AddMonths(-1);

            if (!string.IsNullOrWhiteSpace(Request["dateto"]))
                searchRequest.DateTo = DateTime.ParseExact(Request["dateto"], "ddMMyyyy", System.Globalization.CultureInfo.InvariantCulture);
            if (!string.IsNullOrWhiteSpace(Request["datefrom"]))
                searchRequest.DateFrom = DateTime.ParseExact(Request["datefrom"], "ddMMyyyy", System.Globalization.CultureInfo.InvariantCulture);



            if (!string.IsNullOrWhiteSpace(Request["status"]))
                searchRequest.TransactionStatus = (CustomerTransactionService.TransationSearchRequest.TransactionStatuses)Enum.Parse(typeof(CustomerTransactionService.TransationSearchRequest.TransactionStatuses), Request["status"], true);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pageindex"]))
                searchRequest.PageIndex = Convert.ToInt32(Request.QueryString["pageindex"]);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pagesize"]))
                searchRequest.PageSize = Convert.ToInt32(Request.QueryString["pagesize"]);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["subscriptionplanid"]) && Regex.IsMatch(Request.QueryString["subscriptionplanid"], @"^(\{{0,1}([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}\}{0,1})$"))
                searchRequest.SubscriptionPlanId = new Guid(Request.QueryString["subscriptionplanid"]);

            var searchResult = CustomerTransactionService.TransactionSearch(searchRequest);

            if (!exportToCsv)
                return View(searchResult);

            Response.Clear();
            Response.AddHeader("Content-Disposition", "attachment; filename=payments.csv");
            Response.ContentType = "text/csv";
            Response.Write(Utility.Helpers.CreateCSVAndAppendCustomerFieldsFromGenericList(searchResult.Items, "CustomerId"));                
            Response.End();
            return null;
        }

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/transaction/{customerTransactionId}")]
        public ActionResult View(Guid customerTransactionId)
        {

            var getTransactionResult = CustomerTransactionService.Get(new CustomerTransactionService.GetTransactionRequest { TransactionId = customerTransactionId });
            var getSubscriptionPlanResult = SubscriptionPlanService.Get(new SubscriptionPlanService.GetRequest {  SubscriptionPlanId = getTransactionResult.Transaction.SubscriptionPlanId });

            var result = new TransactionViewViewModel
            {
                Amount = getTransactionResult.Transaction.Amount,
                Batch = getTransactionResult.Transaction.Batch,
                Country = getTransactionResult.Transaction.Country,
                CreatedAt = getTransactionResult.Transaction.CreatedAt,
                Currency = getTransactionResult.Transaction.Currency,
                Description = getTransactionResult.Transaction.Description,
                Provider = getTransactionResult.Transaction.Provider,
                ProviderId = getTransactionResult.Transaction.ProviderId,
                ProviderMessage = getTransactionResult.Transaction.ProviderMessage,
                Reference = getTransactionResult.Transaction.Reference,
                RenewalFrom = getTransactionResult.Transaction.RenewalFrom,
                RenewalTo = getTransactionResult.Transaction.RenewalTo,
                StatementDescription = getTransactionResult.Transaction.StatementDescription,
                Status = getTransactionResult.Transaction.Status,
                SubscriptionPlanId = getTransactionResult.Transaction.SubscriptionPlanId,
                SubscriptionPlanName = getSubscriptionPlanResult.SubscriptionPlan.Name,
                UpdatedAt = getTransactionResult.Transaction.UpdatedAt
            };



            return View(result);
        }


        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/transaction/{customerTransactionId}/refund")]
        public ActionResult IssueRefund(Guid customerTransactionId)
        {
            var customerTransactionGetResponse = CustomerTransactionService.Get(new CustomerTransactionService.GetTransactionRequest
            {
                TransactionId = customerTransactionId
            });

            var model = new TransacrionIssueRefundViewModel
            {
                TransactionAmount = customerTransactionGetResponse.Transaction.Amount,
                TransactionAmountRefunded = customerTransactionGetResponse.Transaction.AmountRefunded,
                TransactionCurrency = customerTransactionGetResponse.Transaction.Currency
            };

            return View(model);
        }

        [HttpPost]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/transaction/{customerTransactionId}/refund")]
        public ActionResult IssueRefund(Guid customerTransactionId, TransacrionIssueRefundViewModel model)
        {
            var customerTransactionGetResponse = CustomerTransactionService.Get(new CustomerTransactionService.GetTransactionRequest
            {
                TransactionId = customerTransactionId
            });

            model.TransactionAmount = customerTransactionGetResponse.Transaction.Amount;
            model.TransactionAmountRefunded = customerTransactionGetResponse.Transaction.AmountRefunded;
            model.TransactionCurrency = customerTransactionGetResponse.Transaction.Currency;

            if (model.RefundAmount > (model.TransactionAmount - model.TransactionAmountRefunded))
                ModelState.AddModelError("RefundAmount", "The maximum amount that can be refunded is " + (model.TransactionAmount - model.TransactionAmountRefunded).ToString("0.00"));

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var issueTransactionRefundResponse = CustomerTransactionRefundService.IssueTransactionRefund(new CustomerTransactionRefundService.IssueTransactionRefundRequest { CustomerTransactionId = customerTransactionId, Amount = model.RefundAmount, Reason = model.RefundReason });
                ViewBag.Success = issueTransactionRefundResponse.TransactionRefund.Status == 1;
                ViewBag.ErrorMessage = issueTransactionRefundResponse.TransactionRefund.ProviderMessage;
            }
            catch (Exception ex)
            {
                ViewBag.Success = false;
                ViewBag.ErrorMessage = ex.Message;
            }

            return View(model);
        }
    }
}

PaymentGateway/Areas/ControlPanel/Views/Transaction/Index.cshtml
@model CustomerTransactionService.TransationSearchResult
@using StreamAMG.OTTPlatform.Core.Services
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Transactions";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
}
<h1>Payments</h1>
<div class="well">
    <form class="form-inline" action="/controlpanel/transaction/">
        <div class="form-group">
            <label for="filter-status">Status</label>
            <select class="form-control" id="filter-status" name="status">
                <option value="">Any Status</option>
                <option value="failure" @(Request.QueryString["status"] == "failure" ? "selected" : "")>Failed</option>
                <option value="success" @(Request.QueryString["status"] == "success" ? "selected" : "")>Successful</option>
                <option value="warning" @(Request.QueryString["status"] == "warning" ? "selected" : "")>Warning</option>
                <option value="processing" @(Request.QueryString["status"] == "processing" ? "selected" : "")>Processing</option>
                <option value="prepared" @(Request.QueryString["status"] == "prepared" ? "selected" : "")>Prepared</option>
            </select>
        </div>
        <div class="form-group">
            <label for="sel1">Subscription Plan</label>
            <select class="form-control" id="sel1" name="subscriptionplanid">
                <option value="">Any Subscription Plan</option>
                @foreach (var item in SubscriptionPlanService.GetSubscriptionPlanList(new SubscriptionPlanService.GetSubscriptionPlanListRequest { PageIndex = 0, PageSize = 20 }).Items)
                {
                    <option value="@item.Id.ToString()" @(Model.Request.SubscriptionPlanId == item.Id ? "selected" : "")>@item.Name Subscription Plan</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="filter-date">Date</label>
            <input type="text" class="form-control" id="filter-date" placeholder="" value="">
            <input type="hidden" id="filter-date-from" value="@Model.Request.DateFrom.Value.ToString("ddMMyyyy")" name="datefrom" />
            <input type="hidden" id="filter-date-to" value="@Model.Request.DateTo.Value.ToString("ddMMyyyy")" name="dateto" />
        </div>
        <button type="submit" class="btn btn-primary">Filter</button>
    </form>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <p>Your search returned @Model.ItemCount payments.</p>
        </div>
    </div>
</div>
@if (Model.ItemCount > 0)
{
    <div class="table-responsive">
        <table id="customersTable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Amount</th>
                    <th>Customer</th>
                    <th>Payment</th>
                    <th>State</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr onclick="eModal.iframe({url: '/controlpanel/transaction/@item.Id?returnurl=@HttpUtility.UrlEncode(Request.RawUrl)', title:'Payment', size: eModal.size.lg});">
                        <td>
                            <strong>@StreamAMG.OTTPlatform.Utility.Helpers.GetCurrencySymbol(item.Currency) @item.Amount.ToString("0.00")</strong><br /> @item.CreatedAt.ToString("ddd d MMM yyyy HH:mm:ss")
                        </td>
                        <td>
                            <strong>@item.CustomerFirstName @item.CustomerLastName </strong> <br /> @item.CustomerEmailAddress
                        </td>
                        <td>
                            <strong>@item.Description</strong><br /> @item.Reference
                        </td>
                        <td>
                            @if (item.SubmittedAt.HasValue)
                            {
                                if (item.Status == -1)
                                {
                                    <span>Failed</span>
                                }
                                else if (item.Status == 1)
                                {
                                    <span>Success</span>
                                }
                                else
                                {
                                    if (item.WarnAt.HasValue && item.WarnAt.Value <= DateTime.UtcNow)
                                    {
                                        <span>Warning</span>
                                    }
                                    else
                                    {
                                        <span>Processing</span>
                                    }
                                    if (item.WarnAt.HasValue)
                                    {
                                        <br /><small>Response expected by @item.WarnAt.Value.ToString("ddd d MMM yyyy HH:mm:ss")</small>
                                    }

                                }
                            }
                            else
                            {
                                <span>Prepared</span>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-actions pull-right">
                <a href="/controlpanel/transaction/?export=csv&@Request.QueryString.ToString()" class="btn btn-info">Export <span class="visible-xxxs">to CSV</span></a>
            </div>
            <div class="form-group">
                @HtmlExtensions.Pager(Model.PageIndex, Model.PageSize, Model.ItemCount)
            </div>
        </div>
    </div>
}

<script>
    $('#filter-date').daterangepicker({
        "autoApply": true,
        "ranges": {
            "This Month": [
                "@DateTime.UtcNow.AddMonths(-1).ToString("ddd d MMM yyyy")",
                "@DateTime.UtcNow.AddMonths(0).ToString("ddd d MMM yyyy")"
            ],
            "Previous Month": [
                "@DateTime.UtcNow.AddMonths(-2).ToString("ddd d MMM yyyy")",
                "@DateTime.UtcNow.AddMonths(-1).ToString("ddd d MMM yyyy")"
            ]
        },
        "locale": {
            "format": "ddd D MMM YYYY",
            "separator": " - ",
            "applyLabel": "Apply",
            "cancelLabel": "Cancel",
            "fromLabel": "From",
            "toLabel": "To",
            "customRangeLabel": "Custom",
            "weekLabel": "W",
            "firstDay": 1
        },
        "showCustomRangeLabel": false,
        "alwaysShowCalendars": true,
        "startDate": "@Model.Request.DateFrom.Value.ToString("ddd d MMM yyyy")",
        "endDate": "@Model.Request.DateTo.Value.ToString("ddd d MMM yyyy")",
        "opens": "left"
    }, function (start, end, label) {
        $("#filter-date-from").val(start.format('DDMMYYYY'));
        $("#filter-date-to").val(end.format('DDMMYYYY'));
    });
</script>

PaymentGateway/Areas/ControlPanel/Views/Transaction/IssueRefund.cshtml
@model StreamAMG.OTTPlatform.Areas.ControlPanel.Models.TransacrionIssueRefundViewModel
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Issue Customer Refund";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Window.cshtml";
}
<p>Complete the form below to issue a refund; the orginal transaction value was @Model.TransactionAmount.ToString("0.00") @Model.TransactionCurrency.</p>

@if (ViewBag.Success == true)
{
    Response.Redirect(Url.Action("View", "Transaction", new { @customerTransactionId = ViewContext.RouteData.Values["customerTransactionId"] }) + "?returnurl="  + HttpUtility.UrlEncode(Request.QueryString["returnurl"]));
}
@if (ViewBag.Success == false)
{
    <div class="alert alert-danger" role="alert">
        <p>The refund could not be issued, because @ViewBag.ErrorMessage</p>
    </div>
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @Html.ValidationSummary()
    </div>
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.TransactionCurrency)
    @Html.HiddenFor(m => m.TransactionAmount)
    @Html.HiddenFor(m => m.TransactionAmountRefunded)
    @Html.HiddenFor(m => m.RefundAmountMax)

    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(m => m.RefundAmount, new { @class = "control-label" }) <label>(@StreamAMG.OTTPlatform.Utility.Helpers.GetCurrencySymbol(Model.TransactionCurrency))</label>
                @Html.TextBoxFor(m => m.RefundAmount, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-sm-9">
            <div class="form-group">
                @Html.LabelFor(m => m.RefundReason, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.RefundReason, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-actions pull-right">
                <button type="submit" class="btn btn-success">Process Refund</button>
            </div>
            <div class="form-actions">
                <a href="@Url.Action("View","Transaction", new { @customerTransactionId = ViewContext.RouteData.Values["customerTransactionId"] })?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">Return to payment</a>
            </div>
        </div>
    </div>
}

PaymentGateway/Areas/ControlPanel/Views/Transaction/View.cshtml
@model StreamAMG.OTTPlatform.Areas.ControlPanel.Models.TransactionViewViewModel
@using StreamAMG.OTTPlatform.Core.Services

@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Payment";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Window.cshtml";
    var TransactionRefundSearchResponse = CustomerTransactionRefundService.TransactionRefundSearch(new CustomerTransactionRefundService.TransationRefundSearchRequest { CustomerTransactionId = new Guid(ViewContext.RouteData.Values["customerTransactionId"].ToString()), TransactionStatus = null, PageIndex = 0, PageSize = int.MaxValue });
}

@if (Model.Status == -1)
{
    <div class="alert alert-danger" role="alert">The payment could not be taken because : @Model.ProviderMessage</div>
}

<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label class="control-label">Description</label>
            <p class="form-control-static">
                @Model.Description
            </p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label class="control-label">Payment method</label>
            <p class="form-control-static">
                @if (Model.Provider == "StripeCard")
                {
                    <span>@Model.Reference</span>
                }
                else if (Model.Provider == "PayPal")
                {
                    <span>PayPal account @Model.Reference</span>
                }
                else
                {
                    <span>@Model.Reference</span>
                }
            </p>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            <label class="control-label">Amount</label>
            <p class="form-control-static">
                @Model.Amount.ToString("0.00")
                @Model.Currency
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label class="control-label">Processor</label>
            <p class="form-control-static">
                @if (Model.Provider == "StripeCard")
                {
                    <span>Stripe, transaction id @(string.IsNullOrWhiteSpace(Model.ProviderId) ? "none" : Model.ProviderId)</span>
                }
                else if (Model.Provider == "PayPal")
                {
                    <span>PayPal, transaction id @(string.IsNullOrWhiteSpace(Model.ProviderId) ? "none" : Model.ProviderId)</span>
                }
                else
                {
                    <span>@Model.Provider, transaction id @(string.IsNullOrWhiteSpace(Model.ProviderId) ? "none" : Model.ProviderId)</span>
                }
            </p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label class="control-label">Date and Time</label>
            <p class="form-control-static">
                @Model.CreatedAt.ToString("ddd d MMM yyyy HH:mm:ss")
            </p>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            <label class="control-label">Status</label>
            <p class="form-control-static">
                @if (Model.Status == -1)
                {
                    <span>Failed</span>
                }
                else if (Model.Status == 1)
                {
                    <span>Success</span>
                }
                else
                {
                    <span>Pending</span>
                }
            </p>
        </div>
    </div>
</div>
<h2>Refunds</h2>
@if (TransactionRefundSearchResponse.ItemCount == 0)
{
    <p>No refunds have been attempted.</p>
}
else
{
    <table id="customersTable" class="table table-striped">
        <thead>
            <tr>
                <th>Amount</th>
                <th>Description</th>
                <th>State</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in TransactionRefundSearchResponse.Items)
            {
                <tr>
                    <td>
                        <strong>@item.Amount.ToString("0.00") @StreamAMG.OTTPlatform.Utility.Helpers.GetCurrencySymbol(item.Currency) </strong><br /> @item.CreatedAt.ToString("ddd d MMM yyyy HH:mm:ss")
                    </td>
                    <td>
                        <strong>@item.Description</strong><br />                        
                        @item.Reason<br />
                        <small class="text-danger">@item.ProviderMessage</small>
                    </td>
                    <td>
                        @if (item.SubmittedAt.HasValue)
                    {
                        if (item.Status == -1)
                        {
                                <span class="text-error">Failed</span>
                            }
                            else if (item.Status == 1)
                            {
                                <span class="text-success">Success</span>
                            }
                            else
                            {
                                if (item.WarnAt.HasValue && item.WarnAt.Value <= DateTime.UtcNow)
                                {
                                    <span class="text-warning">Warning</span>
                                }
                                else
                                {
                                    <span>Processing</span>
                                }
                                if (item.WarnAt.HasValue)
                                {
                                    <br /><small>Response expected by @item.WarnAt.Value.ToString("ddd d MMM yyyy HH:mm:ss")</small>
                                }

                            }
                        }
                        else
                        {
                            <span>Prepared</span>
                        }
                    </td>                   
                </tr>
            }
        </tbody>
    </table>
}
<div class="row">
    <div class="col-md-12">
        <div class="form-actions pull-right">
            <a href="@Url.Action("IssueRefund","Transaction", new { @customerTransactionId = ViewContext.RouteData.Values["customerTransactionId"] })?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])" class="btn btn-info">Refund</a>
        </div>
    </div>
</div>