PaymentGateway/Areas/ControlPanel/Controllers/CustomFieldController.cs
using NLog;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Models;
using StreamAMG.OTTPlatform.Core.Services;
using System;
using System.Linq;
using System.Web.Mvc;
using StreamAMG.OTTPlatform.Core.Models;

namespace StreamAMG.OTTPlatform.Areas.ControlPanel.Controllers
{

    [RouteArea("ControlPanel")]
    public class CustomFieldController : Controller
    {

        #region Index

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/customfield")]
        public ActionResult Index()
        {
            var searchRequest = new CustomFieldService.GetCustomFieldListRequest
            {
                PageIndex = 0,
                PageSize = 20
            };

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pageindex"]))
                searchRequest.PageIndex = Convert.ToInt32(Request.QueryString["pageindex"]);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pagesize"]))
                searchRequest.PageSize = Convert.ToInt32(Request.QueryString["pagesize"]);

            var searchResult = CustomFieldService.GetCustomFieldList(searchRequest);
            return View(searchResult);
        }

        #endregion

        #region View

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/customfield/{customFieldId:guid}/view")]
        public ActionResult View(Guid customFieldId)
        {
            return View();
        }

        #endregion

        #region Edit

        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/customfield/{customFieldId:guid}/edit")]
        public ActionResult Edit(Guid customFieldId)
        {
            var getCustomFieldResponse = CustomFieldService.GetCustomField(new CustomFieldService.GetCustomFieldRequest { CustomFieldId = customFieldId });

            var model = new CustomFieldEditViewModel
            {
                DisplayOrder = getCustomFieldResponse.CustomField.DisplayOrder,
                Label = getCustomFieldResponse.CustomField.Label,
                Required = getCustomFieldResponse.CustomField.Required,
                RequiredMessage = getCustomFieldResponse.CustomField.RequiredMessage
            };

            foreach (var option in getCustomFieldResponse.CustomField.Options)
            {
                model.Options.Add( new CustomFieldEditViewModel.Option
                {
                    Id = option.Id,
                    DisplayValue = option.DisplayValue,
                    ReportingValue = option.ReportingValue
                });
            }

            return View(model);
        }

        [HttpPost]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/customfield/{customFieldId:guid}/edit")]
        public ActionResult Edit(Guid customFieldId, CustomFieldEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var getCustomFieldResponse = CustomFieldService.GetCustomField(new CustomFieldService.GetCustomFieldRequest { CustomFieldId = customFieldId });

            getCustomFieldResponse.CustomField.DisplayOrder = model.DisplayOrder;
            getCustomFieldResponse.CustomField.Label = model.Label;
            getCustomFieldResponse.CustomField.Required = model.Required;
            getCustomFieldResponse.CustomField.RequiredMessage = model.RequiredMessage;

            getCustomFieldResponse.CustomField.Options.Clear();

            foreach (var option in model.Options)
            {
                getCustomFieldResponse.CustomField.Options.Add( new CustomFieldModel.Option
                {
                    Id = option.Id,
                    DisplayValue = option.DisplayValue,
                    ReportingValue = option.ReportingValue
                });
            }

            try
            {
                CustomFieldService.SetCustomField(new CustomFieldService.SetCustomFieldRequest
                {
                    CustomFieldId = customFieldId,
                    CustomField = getCustomFieldResponse.CustomField
                });
                ViewBag.Success = true;
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to save Custom Field. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }

            return View(model);
        }

        [HttpPost]
        [Route("~/controlpanel/customfield/{customFieldId:guid}/edit/option")]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        public ActionResult EditAddOption()
        {
            return PartialView("EditOption", new CustomFieldEditViewModel.Option { Id = Guid.NewGuid() });
        }

        #endregion

        #region EditTransaltion


        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/customfield/{customFieldId:guid}/translate/{language}")]
        public ActionResult EditTransaltion(Guid customFieldId, string language)
        {
            var getCustomFieldResponse = CustomFieldService.GetCustomField(
               new CustomFieldService.GetCustomFieldRequest
               {
                   CustomFieldId = customFieldId
               }
           );
            
            var getCustomFieldTransaltionResponse = CustomFieldService.GetCustomFieldTranslation(
                new CustomFieldService.GetCustomFieldTransaltionRequest
                {
                    CustomFieldId = customFieldId,
                    Language = language,
                    
                }
            );

            var model = new CustomFieldEditTranslationViewModel
            {
                DisplayOrderOriginal = getCustomFieldResponse.CustomField.DisplayOrder,
                Label = getCustomFieldTransaltionResponse.CustomFieldTransaltion.Label,
                LabelOriginal = getCustomFieldResponse.CustomField.Label,
                RequiredMessage = getCustomFieldTransaltionResponse.CustomFieldTransaltion.RequiredMessage,
                RequiredMessageOriginal = getCustomFieldResponse.CustomField.RequiredMessage,
                RequiredOriginal = getCustomFieldResponse.CustomField.Required
            };

            foreach (var option in getCustomFieldResponse.CustomField.Options)
            {
                var optionTransalted = getCustomFieldTransaltionResponse.CustomFieldTransaltion.Options.FirstOrDefault(x => x.Id == option.Id);

                model.Options.Add(new CustomFieldEditTranslationViewModel.Option
                {
                    Id = option.Id,
                    DisplayValueOriginal = option.DisplayValue,
                    DisplayValue = optionTransalted == null ? "" : optionTransalted.DisplayValue,
                    ReportingValueOriginal = option.ReportingValue
                });
            }

            return View(model);
        }

        [HttpPost]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/customfield/{customFieldId:guid}/translate/{language}")]
        public ActionResult EditTransaltion(Guid customFieldId, string language, CustomFieldEditTranslationViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var getCustomFieldTranslationResponse = CustomFieldService.GetCustomFieldTranslation(new CustomFieldService.GetCustomFieldTransaltionRequest { CustomFieldId = customFieldId, Language = language });

            getCustomFieldTranslationResponse.CustomFieldTransaltion.Label = model.Label;
            getCustomFieldTranslationResponse.CustomFieldTransaltion.RequiredMessage = model.RequiredMessage;

            getCustomFieldTranslationResponse.CustomFieldTransaltion.Options.Clear();

            foreach (var option in model.Options)
            {
                getCustomFieldTranslationResponse.CustomFieldTransaltion.Options.Add(new CustomFieldTransaltionModel.Option
                {
                    Id = option.Id,
                    DisplayValue = option.DisplayValue,                    
                });
            }
            
            try
            {
                CustomFieldService.SetCustomFieldTranslation(new CustomFieldService.SetCustomFieldTransaltionRequest
                {
                    CustomFieldId = customFieldId,
                    Language = language,
                    CustomFieldTransaltion = getCustomFieldTranslationResponse.CustomFieldTransaltion
                });
                ViewBag.Success = true;
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to save Custom Field Transaltion. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }
            
            return View(model);
        }

        #endregion
    }
}

PaymentGateway/Areas/ControlPanel/Views/CustomField/Edit.cshtml
@model StreamAMG.OTTPlatform.Areas.ControlPanel.Models.CustomFieldEditViewModel
@using StreamAMG.OTTPlatform.Core.Services
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Custom Field";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
    var CurrentCustomField = CustomFieldService.GetCustomField(new CustomFieldService.GetCustomFieldRequest { CustomFieldId = new Guid(ViewContext.RouteData.Values["customFieldId"].ToString()) }).CustomField;
}
<div class="btn-group pull-right">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            if ((ViewContext.RouteData.Values["language"] == null && StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language)) || (ViewContext.RouteData.Values["language"] != null && language == ViewContext.RouteData.Values["language"].ToString()))
            {
                <img src="/areas/controlpanel/_resx/images/languages/@(language).png" /> @(StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language)) <span class="caret"></span>
            }
        }
    </button>
    <ul class="dropdown-menu">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            <li>
                <a href="/controlpanel/customfield/@ViewContext.RouteData.Values["customFieldId"]@( StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language) ? "/edit/" : "/translate/" + language)/?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">
                    <img src="/areas/controlpanel/_resx/images/languages/@(language).png" />
                    @( StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language))
                </a>
            </li>
        }
    </ul>
</div>
<h1>@CurrentCustomField.Name</h1>
<p>Please complete for form below to make changes to the custom field '<b><i>@CurrentCustomField.Name</i></b>', changes made may be cached.</p>
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @Html.ValidationSummary()
    </div>
}
@if (ViewBag.Success == true)
{
    <div class="alert alert-success" role="alert">
        <p>Your changes were successfully saved.</p>
    </div>
}
@if (ViewBag.Success == false)
{
    <div class="alert alert-danger" role="alert">
        <p>Your changes could not be saved please try again.</p>
    </div>
}
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Label, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Label, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.DisplayOrder, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.DisplayOrder, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <h2>Validation</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Required, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.Required, new SelectList(new[] { new { Value = "true", Text = "Yes, the field is mandataory" }, new { Value = "false", Text = "No, the field is optional" } }, "Value", "Text", 1), "", new { @class = "form-control" })                
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.RequiredMessage, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.RequiredMessage, new { @class = "form-control" })
            </div>
        </div>
        
    </div>
    <h2>Options</h2>
    <p>Options can be ordered by dragging and dropping the rows.</p>
    <ul id="optionsEditor" style="list-style-type: none; padding: 0;">
        @foreach (var option in Model.Options)
        {
            Html.RenderPartial("EditOption", option);
        }
    </ul>
    <a id="optionsEditorAdd" href="#">Add another option</a>
    <div class="row">
        <div class="col-md-12">
            <div class="form-actions pull-right">
                <button type="submit" class="btn btn-info">Save <span class="visible-xxxs">changes</span></button>
            </div>
            <div class="form-group">
                <a href="@Url.Action("View", "CustomField", new { @customFieldId = ViewContext.RouteData.Values["customFieldId"] })?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">Return to custom field details</a>
            </div>
        </div>
    </div>
}
<script>
    $("#optionsEditorAdd").click(function () {
        $.post('@Url.Action("EditAddOption", "CustomField")', function (v) { $("#optionsEditor").append(v); });
        return false;
    });

  $( function() {
      $("#optionsEditor").sortable();
      $("#optionsEditor").disableSelection();
  } );
</script>

PaymentGateway/Areas/ControlPanel/Views/CustomField/EditOption.cshtml
@using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
@model  StreamAMG.OTTPlatform.Areas.ControlPanel.Models.CustomFieldEditViewModel.Option

<li style="padding-bottom: 15px" >
    @using (Html.BeginCollectionItem("Options"))
    {
        <div class="row">
            @Html.HiddenFor(m => m.Id)
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.ReportingValue, new { @class = "control-label" }) <small>used for reporting</small>
                    @Html.TextBoxFor(m => m.ReportingValue, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ReportingValue)
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.DisplayValue, new { @class = "control-label" }) <small>presented to the user</small>
                    @Html.TextBoxFor(m => m.DisplayValue, new { @class = "form-control" })
                </div>
            </div>                
        </div>
    <a href="#" onclick="$(this).parent().remove();return false;">Delete</a>
    }
</li>

PaymentGateway/Areas/ControlPanel/Views/CustomField/EditTransaltion.cshtml
@model StreamAMG.OTTPlatform.Areas.ControlPanel.Models.CustomFieldEditTranslationViewModel
@using StreamAMG.OTTPlatform.Core.Services
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Custom Field";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";

    var CurrentCustomField = CustomFieldService.GetCustomField(new CustomFieldService.GetCustomFieldRequest { CustomFieldId = new Guid(ViewContext.RouteData.Values["customFieldId"].ToString()) }).CustomField;
}

<div class="btn-group pull-right">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            if ((ViewContext.RouteData.Values["language"] == null && StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language)) || (ViewContext.RouteData.Values["language"] != null && language == ViewContext.RouteData.Values["language"].ToString()))
            {
                <img src="/areas/controlpanel/_resx/images/languages/@(language).png" /> @(StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language)) <span class="caret"></span>
            }
        }
    </button>
    <ul class="dropdown-menu">
        @foreach (var language in StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageCodes)
        {
            <li>
                <a href="/controlpanel/customfield/@ViewContext.RouteData.Values["customFieldId"]@( StreamAMG.OTTPlatform.Utility.SystemLanguages.IsDefaultLanguage(language) ? "/edit/" : "/translate/" + language)/?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">
                    <img src="/areas/controlpanel/_resx/images/languages/@(language).png" />
                    @( StreamAMG.OTTPlatform.Utility.SystemLanguages.LanguageName(language))
                </a>
            </li>
        }
    </ul>
</div>
<h1>@CurrentCustomField.Name</h1>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @Html.ValidationSummary()
    </div>
}
@if (ViewBag.Success == true)
{
    <div class="alert alert-success" role="alert">
        <p>Your changes were successfully saved.</p>
    </div>
}

@if (ViewBag.Success == false)
{
    <div class="alert alert-danger" role="alert">
        <p>Your changes could not be saved please try again.</p>
    </div>
}
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Label, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Label, new { @class = "form-control", @placeholder = Model.LabelOriginal })
                @Html.HiddenFor(m => m.LabelOriginal)
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.DisplayOrderOriginal, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.DisplayOrderOriginal, new { @class = "form-control", @readonly = "true" })
            </div>
        </div>
    </div>
    <h2>Validation</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.RequiredOriginal, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.RequiredOriginal, new SelectList(new[] { new { Value = "true", Text = "Yes, the field is mandataory" }, new { Value = "false", Text = "No, the field is optional" } }, "Value", "Text", 1), "", new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.RequiredMessage, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.RequiredMessage, new { @class = "form-control", @placeholder = Model.RequiredMessageOriginal })
                @Html.HiddenFor(m => m.RequiredMessageOriginal)
            </div>
        </div>

    </div>
    <h2>Options</h2>    
    <ul id="optionsEditor" style="list-style-type: none; padding: 0;">
        @foreach (var option in Model.Options)
        {
            Html.RenderPartial("EditTranslationOption", option);
        }
    </ul>    
    <div class="row">
        <div class="col-md-12">
            <div class="form-actions pull-right">
                <button type="submit" class="btn btn-info">Save <span class="visible-xxxs">changes</span></button>
            </div>
            <div class="form-group">
                <a href="@Url.Action("View", "CustomField", new { @customFieldId = ViewContext.RouteData.Values["customFieldId"] })?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])">Return to custom field details</a>
            </div>
        </div>
    </div>
}

PaymentGateway/Areas/ControlPanel/Views/CustomField/EditTranslationOption.cshtml
@using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
@model  StreamAMG.OTTPlatform.Areas.ControlPanel.Models.CustomFieldEditTranslationViewModel.Option

<li style="padding-bottom: 15px" >
    @using (Html.BeginCollectionItem("Options"))
    {
        <div class="row">
            @Html.HiddenFor(m => m.Id)
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.ReportingValueOriginal, new { @class = "control-label" }) <small>used for reporting</small>
                    @Html.TextBoxFor(m => m.ReportingValueOriginal, new { @class = "form-control", @readonly = "readonly" })                    
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.DisplayValue, new { @class = "control-label" }) <small>presented to the user</small>
                    @Html.TextBoxFor(m => m.DisplayValue, new { @class = "form-control", @placeholder = Model.DisplayValueOriginal })
                    @Html.HiddenFor(m => m.DisplayValueOriginal)
                </div>
            </div>                
        </div>    
    }
</li>

PaymentGateway/Areas/ControlPanel/Views/CustomField/Index.cshtml
@model CustomFieldService.GetCustomFieldListResponse
@using StreamAMG.OTTPlatform.Core.Services;
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Custom Field";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
}
<h1>Custom Fields</h1>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <p>Your search returned @Model.ItemCount custom fields.</p>
        </div>
    </div>
</div>
@if (Model.ItemCount > 0)
{
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Input Type</th>
                    <th>Label</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr onclick="document.location.href = '@Url.Action("Edit", "CustomField", new { @customFieldId = item.Id })?returnurl=@HttpUtility.UrlEncode(Request.RawUrl)';">
                        <td>@item.Name</td>
                        <td>@item.InputType</td>
                        <td>@item.Label</td>
                        </tr>
                }
            </tbody>
        </table>
    </div>
    @HtmlExtensions.Pager(Model.PageIndex, Model.PageSize, Model.ItemCount)
}

PaymentGateway/Areas/ControlPanel/Views/CustomField/View.cshtml
@using StreamAMG.OTTPlatform.Core.Services
@{
    ViewBag.SiteName = System.Configuration.ConfigurationManager.AppSettings["SiteName"];
    ViewBag.Title = ViewBag.SiteName + " > Custom Field";
    Layout = "~/Areas/ControlPanel/Views/Shared/_Layout.cshtml";
    var CurrentCustomField = CustomFieldService.GetCustomField(new CustomFieldService.GetCustomFieldRequest { CustomFieldId = new Guid(ViewContext.RouteData.Values["customFieldId"].ToString()) }).CustomField;
}

<h1>@CurrentCustomField.Name</h1>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">Label</label>
            <p class="form-control-static">
                @CurrentCustomField.Label
            </p>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">Display Order</label>
            <p class="form-control-static">
               @CurrentCustomField.DisplayOrder
            </p>
        </div>
    </div>
</div>
<h2>Options</h2>
@if (CurrentCustomField.Options.Count == 0)
{
    <p>There are currently no options assigned to this field, edit teh field to add new options.</p>
}
else
{ 
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Value</th>
            <th>Text</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var option in CurrentCustomField.Options)
        {
            <tr>
                <td>@option.ReportingValue</td>
                <td>@option.DisplayValue</td>
            </tr>
        }
        </tbody>
    </table>
}
<div class="row">
    <div class="col-md-12">
        <div class="form-actions pull-right">
            <a href="@Url.Action("Edit","CustomField", new { @customFieldId = new Guid(ViewContext.RouteData.Values["customFieldId"].ToString()) })?returnurl=@HttpUtility.UrlEncode(Request.QueryString["returnurl"])" class="btn btn-info">Edit Custom Field</a>
        </div>
        <div class="form-actions">
            <a href="@Request.QueryString["returnurl"]">Return to custom field list</a>
        </div>
    </div>
</div>