PaymentGateway/Areas/ControlPanel/Controllers/OfferController.cs
using NLog;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Models;
using StreamAMG.OTTPlatform.Core.Models;
using StreamAMG.OTTPlatform.Core.Services;
using System;
using System.Web.Mvc;

namespace StreamAMG.OTTPlatform.Areas.ControlPanel.Controllers
{
    [RouteArea("ControlPanel")]
    public class OfferController : Controller
    {
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer")]
        public ActionResult Index()
        {
            var searchRequest = new OfferService.GetOfferListRequest
            {
                PageIndex = 0,
                PageSize = 20
            };

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pageindex"]))
                searchRequest.PageIndex = Convert.ToInt32(Request.QueryString["pageindex"]);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pagesize"]))
                searchRequest.PageSize = Convert.ToInt32(Request.QueryString["pagesize"]);

            var searchResult = OfferService.GetOfferList(searchRequest);

            return View(searchResult);
        }


        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/{offerId}")]
        public ActionResult View(Guid offerId)
        {
            var ExportToCsv = !string.IsNullOrWhiteSpace(Request.QueryString["export"]);
            var getOfferResult = OfferService.Get(new OfferService.GetRequest { OfferId = offerId });
            var model = new OfferViewModel
            {
                AppliesFor = getOfferResult.Offer.AppliesFor,
                Discount = getOfferResult.Offer.Discount,
                Name = getOfferResult.Offer.Name

            };

            if (ExportToCsv)
            {
                var getOfferListRequest = new OfferVoucherService.GetOfferVoucherListRequest { PageIndex = 0, PageSize = int.MaxValue, OfferId = offerId };

                if (!string.IsNullOrWhiteSpace(Request.QueryString["pageindex"]))
                {
                    getOfferListRequest.PageIndex = Convert.ToInt32(Request.QueryString["pageindex"]);
                }

                var getOfferListResult = OfferVoucherService.GetOfferVoucherList(getOfferListRequest);

                Response.Clear();
                Response.AddHeader("Content-Disposition", "attachment; filename=vouchers.csv");
                Response.ContentType = "text/csv";
                Response.Write(Utility.Helpers.CreateCSVFromGenericList(getOfferListResult.Items));
                Response.End();
            }

            return View(model);
        }



        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/{offerId}/edit")]
        public ActionResult Edit(Guid offerId)
        {
            var getOfferResult = OfferService.Get(new OfferService.GetRequest { OfferId = offerId });
            var model = new OfferEditViewModel
            {
                AppliesFor = getOfferResult.Offer.AppliesFor,                
                AppliesToSubscriptionPlanId = getOfferResult.Offer.SubscriptionPlanId,
                Discount = getOfferResult.Offer.Discount,
                Name = getOfferResult.Offer.Name
            };
            return View(model);
        }

        [HttpPost ValidateInput(false)]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/{offerId}/edit")]
        public ActionResult Edit(Guid offerId, OfferEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var setOfferResult = OfferService.Set(
                    new OfferService.SetRequest
                    {
                        OfferId = offerId,
                        Offer = new OfferModel
                        {
                            AppliesFor = model.AppliesFor,
                            Discount = model.Discount,
                            Name = model.Name,
                            SubscriptionPlanId = model.AppliesToSubscriptionPlanId
                        }
                    }
                );

                ViewBag.Success = true;

            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to save changes to the new offer '" + offerId + "'. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }


            return View(model);
        }


        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/create")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost ValidateInput(false)]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/create")]
        public ActionResult Create(OfferCreateViewModel model)
        {
            if(!ModelState.IsValid)
                return View(model);

            try
            {
                var offerSetResponse = OfferService.Set(new OfferService.SetRequest
                {
                    OfferId = Guid.Empty,
                    Offer = new OfferModel
                    {
                        AppliesFor = model.AppliesFor,
                        Discount = model.Discount,
                        Name = model.Name,
                        SubscriptionPlanId = model.AppliesToSubscriptionPlanId
                    }
                }
                );

                return RedirectToAction("View", new { offerId = offerSetResponse.Offer.Id });
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to create a new offer. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }
            return View(model);
        }

       
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/{offerId}/issue")]
        public ActionResult Issue(Guid offerId)
        {
            return View();
        }

        [HttpPost ValidateInput(false)]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/offer/{offerId}/issue")]
        public ActionResult Issue(Guid offerId, OfferIssueViewModel model)
        {            
            if(!ModelState.IsValid)
                return View(model);


            try
            {
                OfferVoucherService.CreateOfferVoucher(
                    new OfferVoucherService.CreateOfferVoucherRequest
                    {
                        OfferId = offerId,
                        Campaign = model.Campaign,
                        QuantityToCreate = model.Quantity,
                        ValidFrom = DateTime.UtcNow,
                        ValidTo = DateTime.UtcNow.AddMonths(12)
                    }
                );
                return RedirectToAction("View", new { offerId = offerId });
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to create a new offer. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }

            return View(model);
        }

    }
}

PaymentGateway/Areas/ControlPanel/Controllers/UserController.cs
using StreamAMG.OTTPlatform.Areas.ControlPanel.Infrastructure;
using StreamAMG.OTTPlatform.Core.Services;
using System;
using System.Web.Mvc;
using NLog;
using StreamAMG.OTTPlatform.Areas.ControlPanel.Models;
using StreamAMG.OTTPlatform.Core.Models;

namespace StreamAMG.OTTPlatform.Areas.ControlPanel.Controllers
{
    [RouteArea("ControlPanel")]
    public class UserController : Controller
    {
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/user")]
        public ActionResult Index()
        {
            var searchRequest = new UserService.GetUserListRequest
            {
                PageIndex = 0,
                PageSize = 20
            };

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pageindex"]))
                searchRequest.PageIndex = Convert.ToInt32(Request.QueryString["pageindex"]);

            if (!string.IsNullOrWhiteSpace(Request.QueryString["pagesize"]))
                searchRequest.PageSize = Convert.ToInt32(Request.QueryString["pagesize"]);

            var searchResult = UserService.GetUserList(searchRequest);

            return View(searchResult);
        }


        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/user/{userId}/edit")]
        public ActionResult Edit(Guid userId)
        {
            

            var getUserResponse = UserService.Get(new UserService.GetRequest {UserId = userId});


            var model = new UserEditViewModel
            {
                Name = getUserResponse.User.Name,
                Surname = getUserResponse.User.Surname,
                MobilePhone = getUserResponse.User.MobilePhone,
                EmailAddress = getUserResponse.User.EmailAddress,
                Username = getUserResponse.User.Username,
                SystemRoleIds = getUserResponse.User.SystemRoleIds
            };
            
            return View(model);
        }

        [HttpPost]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/user/{userId}/edit")]
        public ActionResult Edit(Guid userId, UserEditViewModel model)
        {

            if (!ModelState.IsValid)
                return View(model);

            var getUserNameIsUniqueResponse = UserService.GetIsUsernameUnique(new UserService.GetIsUsernameUniqueRequest {
                Username = model.Username,
                UserId = userId
            });

            if(!getUserNameIsUniqueResponse.IsUnique)
                ModelState.AddModelError("username","The username is already in use.");

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var setUserResponse = UserService.Set(new UserService.SetRequest
                {
                    UserId = userId,
                    User = new UserModel
                    {
                        Name = model.Name,
                        Surname = model.Surname,
                        MobilePhone = model.MobilePhone,
                        EmailAddress = model.EmailAddress,
                        Username = model.Username,
                        SystemRoleIds = model.SystemRoleIds
                       
                    }
                });

                ViewBag.Success = true;
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to save a new user. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }

            return View(model);
        }



        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/user/create")]
        public ActionResult Create()
        {
            var model = new UserEditViewModel();
            

            return View(model);
        }

        [HttpPost]
        [ControlPanelRequireHttps]
        [ControlPanelAuthrorize("administrator")]
        [Route("~/controlpanel/user/create")]
        public ActionResult Create(UserEditViewModel model)
        {
            if(!ModelState.IsValid)
                return View(model);

            var getUserNameIsUniqueResponse = UserService.GetIsUsernameUnique(new UserService.GetIsUsernameUniqueRequest
            {
                Username = model.Username,
                UserId = Guid.Empty
            });

            if (!getUserNameIsUniqueResponse.IsUnique)
                ModelState.AddModelError("username", "The username is already in use.");

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var setUserResponse = UserService.Set(new UserService.SetRequest
                {
                    UserId = Guid.Empty,
                    User = new UserModel
                    {
                        Name = model.Name,
                        Surname = model.Surname,
                        MobilePhone = model.MobilePhone,
                        EmailAddress = model.EmailAddress,
                        Username = model.Username,
                        SystemRoleIds = model.SystemRoleIds
                    }
                });

                ViewBag.Success = true;
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Unable to create a new user. Exception: {0}", ex.Message);
                ViewBag.Success = false;
            }

            if(ViewBag.Success == true)
                return Redirect(Request["returnurl"]);

            return View(model);
        }
    }
}

PaymentGateway/Areas/ControlPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/areas/controlpanel/_resx/css/theme.css" rel="stylesheet" />    
    <link href="/areas/controlpanel/_resx/css/daterangepicker.css" rel="stylesheet" />    
    <link href="/areas/controlpanel/_resx/css/bootstrap-select.1.11.0.css" rel="stylesheet" />    

    <script src="/areas/controlpanel/_resx/js/jquery-2.2.4.min.js"></script>
    <script src="/areas/controlpanel/_resx/js/jquery-1.12.0.min.js"></script>
    <script src="/areas/controlpanel/_resx/js/modernizr.js"></script>
    <script src="/areas/controlpanel/_resx/js/bootstrap.min.js"></script>    
    <script src="/areas/controlpanel/_resx/js/jquery-ui.min.js"></script>   
    <script src="/areas/controlpanel/_resx/js/script.js"></script>   
    <script src="/areas/controlpanel/_resx/js/emodal.js"></script>   
    
    <script src="/areas/controlpanel/_resx/js/sprintf.js"></script>   
    <script src="/areas/controlpanel/_resx/js/moment.js"></script>   
    <script src="/areas/controlpanel/_resx/js/daterangepicker.js"></script>   
    <script src="/areas/controlpanel/_resx/js/bootstrap-select.1.11.0.js"></script>
</head>
<body style="min-height: 2000px;padding-top: 55px;">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/controlpanel/">@System.Configuration.ConfigurationManager.AppSettings["SiteName"]</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">                
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Customers<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index","Customer")">Customer Accounts</a></li>
                        </ul>
                    </li> 
                  
                     
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Logs<span class="caret"></span></a>
                        <ul class="dropdown-menu">                                               
                            <li class="dropdown-header">Payments</li>         
                            <li><a href="/controlpanel/transaction/">All</a></li>                            
                            <li><a href="/controlpanel/transaction/?status=failure">Failed</a></li>
                            <li><a href="/controlpanel/transaction/?status=success">Successful</a></li>
                            <li><a href="/controlpanel/transaction/?status=warning">Warning</a></li>                            
                            <li><a href="/controlpanel/transaction/?status=processing">Processing</a></li>         
                            <li><a href="/controlpanel/transaction/?status=prepared">Prepared</a></li>
                            <li class="dropdown-header">Refunds</li>         
                            <li><a href="/controlpanel/transactionrefund/">All</a></li>
                            <li><a href="/controlpanel/transactionrefund/?status=failure">Failed</a></li>
                            <li><a href="/controlpanel/transactionrefund/?status=success">Successful</a></li>
                            <li><a href="/controlpanel/transactionrefund/?status=warning">Warning</a></li>
                            <li><a href="/controlpanel/transactionrefund/?status=processing">Processing</a></li>
                            <li><a href="/controlpanel/transactionrefund/?status=prepared">Prepared</a></li>
                            <li class="dropdown-header">Emails</li>
                            <li><a href="/controlpanel/maillog/">All</a></li>
                            <li><a href="/controlpanel/maillog/?status=rejected">Rejected</a></li>
                            <li><a href="/controlpanel/maillog/?status=failed">Failed</a></li>
                            <li><a href="/controlpanel/maillog/?status=sent">Sent</a></li>
                            <li><a href="/controlpanel/maillog/?status=delivered">Delivered</a></li>
                            <li><a href="/controlpanel/maillog/?status=opened">Opened</a></li>
                            <li><a href="/controlpanel/maillog/?status=interacted">Interacted</a></li>                            
                        </ul>
                    </li> 
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Configuration<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/controlpanel/subscriptionplans">Subscription Plans</a></li>
                            <li><a href="@Url.Action("Index","Offer")">Offers</a></li>
                            <li><a href="@Url.Action("Index","CustomField")">Custom Fields</a></li>
                            <li><a href="/controlpanel/mailtemplate">Email Templates</a></li>
                            <li><a href="@Url.Action("Index","User")">Manage Users</a></li>
                        </ul>
                    </li>                    
                    <li><a href="/controlpanel/logout">Logout</a></li>
                </ul>              
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <div class="@Html.Raw(ViewBag.FullWidth != true ? "container" : "")">
        @RenderBody()
    </div>
    <script>
        $(document).ready(function () {
            $("input[data-val-length-max]").each(function () {
                var $this = $(this);
                var data = $this.data();
                $this.attr("maxlength", data.valLengthMax);
            });
        });
    </script>
</body>
</html>

PaymentGateway/Areas/ControlPanel/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>@ViewBag.Title</title>
               
    <link href="/areas/controlpanel/_resx/css/bootstrap.min.css" rel="stylesheet" />
  
    <script src="/areas/controlpanel/_resx/js/jquery-2.2.4.min.js"></script> 
    <script src="/areas/controlpanel/_resx/js/bootstrap.min.js"></script>
  
    <script>
        $(document).ready(function () {
            $("input[data-val-length-max]").each(function () {
                var $this = $(this);
                var data = $this.data();
                $this.attr("maxlength", data.valLengthMax);
            });
        });
    </script>

    <style type="text/css">
        @@media (min-width: 768px) {
            .container {
                width: 450px;
            }
        }

        @@media (min-width: 992px) {
            .container {
                width: 450px;
            }
        }

        @@media (min-width: 1200px) {
            .container {
                width: 450px;
            }
        }
    </style>
</head>
<body>    
    @RenderBody()    
</body>
</html>

PaymentGateway/Areas/ControlPanel/Views/Shared/_Window.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
    <link href="/areas/controlpanel/_resx/css/theme.css" rel="stylesheet" />

    <script src="/areas/controlpanel/_resx/js/jquery-2.2.4.min.js"></script>
    <script src="/areas/controlpanel/_resx/js/modernizr.js"></script>
    <script src="/areas/controlpanel/_resx/js/bootstrap.min.js"></script>
    <script src="/areas/controlpanel/_resx/js/jquery-ui.min.js"></script>
    <script src="/areas/controlpanel/_resx/js/script.js"></script>
    <script src="/areas/controlpanel/_resx/js/emodal.js"></script>
    <style>
        body {
            padding: 10px;
        }
    </style>
</head>
<body>
    
        @RenderBody()
    
    <script>
        $(document).ready(function () {
            $("input[data-val-length-max]").each(function () {
                var $this = $(this);
                var data = $this.data();
                $this.attr("maxlength", data.valLengthMax);
            });
        });
    </script>
</body>
</html>